version: "3.7"
services:
    #database
    mariadb:
      build: ./mariadb
      ports:
        - "3306:3306"
      volumes:
        - ./mariadb/instance:/var/lib/mysql:rw
        # MySQL config
        - ./mariadb/config/local.cnf:/etc/mysql/conf.d/local.cnf:ro
      env_file:
        - ./mariadb/credentials.env
    
    # php-fpm
    php:
      build: ./php-fpm
      ports:
        - "9000"
        - "9009:9009"
      volumes:
        - ./app/src:/var/www/html:rw
        # php.ini
        - ./php-fpm/config/php.ini:/usr/local/etc/php/php.ini:ro
      env_file:
        - ./mysql/credentials.env
        - ./php-fpm/paths.env
      depends_on:
        - mysql

    # web server
    nginx:
      build: ./nginx
      ports:
        - "80:80"
        - "443:443"
      volumes:
        # app
        - ./app/src:/var/www/html:rw
        # nginx configs
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
        # certificates
        - ./nginx/ca/server.crt/:/etc/nginx/server.crt:ro
        - ./nginx/ca/server.key/:/etc/nginx/server.key:ro
      depends_on:
        - php
